import { Anton, Manrope } from "next/font/google";
import "@/styles/globals.css";
import { Footer } from "@/components/Footer/Footer";

const anton = Anton({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-anton",
});

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr" className={`${anton.variable} ${manrope.variable}`}>
      <body>
        <>{children}</>
        <Footer />
      </body>
    </html>
  );
}
